FROM php:7.4-fpm-alpine3.13

RUN set -eux; \
    apk upgrade --no-cache --update \
    && apk add --no-cache \
        $PHPIZE_DEPS \
        zip unzip libzip-dev postgresql-dev \
    && pecl install xdebug-2.9.5 \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-enable opcache \
    && docker-php-ext-install pdo_pgsql \
    && docker-php-ext-install zip

WORKDIR /var/www/index

COPY ./docker/php/configs/xdebug.ini ${PHP_INI_DIR}/conf.d/docker-php-ext-xdebug.ini

COPY --from=composer:1 /usr/bin/composer /usr/bin/composer

COPY docker/php/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint

ENTRYPOINT ["docker-entrypoint"]

CMD ["php-fpm"]
