FROM php:7.4-fpm-alpine3.13

RUN set -eux; \
    apk upgrade --no-cache --update \
    && apk add --no-cache \
        zip unzip libzip-dev postgresql-dev \
    && docker-php-ext-enable opcache \
    && docker-php-ext-install pdo_pgsql \
    && docker-php-ext-install zip

WORKDIR /var/www/index

COPY . .

COPY --from=composer:1 /usr/bin/composer /usr/bin/composer

COPY docker/php/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint

ENTRYPOINT ["docker-entrypoint"]

CMD ["php-fpm"]
