FROM php:7.4-fpm-alpine

RUN apk upgrade --no-cache --update \
    && apk add --no-cache \
        $PHPIZE_DEPS \
        zip unzip libzip-dev \
    && docker-php-ext-enable opcache \
    && docker-php-ext-install zip

WORKDIR /var/www/index

COPY . .

COPY --from=composer:1 /usr/bin/composer /usr/bin/composer

COPY docker/php/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint

ENTRYPOINT ["docker-entrypoint"]

CMD ["php-fpm"]
