FROM php:7.4-fpm-alpine

COPY ./docker/php/configs/xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

RUN apk upgrade --no-cache --update \
    && apk add --no-cache \
        $PHPIZE_DEPS \
        zip unzip libzip-dev postgresql-dev \
    && pecl install xdebug-2.9.5 \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-enable opcache \
    && docker-php-ext-install pdo_pgsql \
    && docker-php-ext-install zip

WORKDIR /var/www/index

COPY . .

COPY --from=composer:1 /usr/bin/composer /usr/bin/composer

RUN composer install

ENTRYPOINT php-fpm -F
