version: "3.7"

services:
    nginx:
        image: nginx:alpine
        depends_on:
            - php
            - db
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/index

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile.${APP_ENV}
        restart: on-failure
        environment:
            APP_ENV: ${APP_ENV}
            PSQL_HOST: ${PSQL_HOST}
            PSQL_PORT: ${PSQL_PORT}
            TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
            DATABASE_URL: postgres://${PSQL_USER}:${PSQL_PASSWORD}@${PSQL_HOST}:${PSQL_PORT}/${PSQL_DATABASE}
            XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST:-127.0.0.1}
            PHP_IDE_CONFIG: 'serverName=${XDEBUG_REMOTE_HOST:-host.docker.internal}'
        volumes:
            - ./:/var/www/index

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: ${PSQL_DATABASE}
            POSTGRES_USER: ${PSQL_USER}
            POSTGRES_PASSWORD: ${PSQL_PASSWORD}
        ports:
            - ${PSQL_PORT}:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: {}
