<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ2c3zU1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ2c3zU1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ2c3zU1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ2c3zU1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQ2c3zU1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Q2c3zU1',
    'container.build_id' => '1702a65e',
    'container.build_time' => 1555593886,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ2c3zU1');
